Laravel 9 support
pestphp/pest-plugin-laravel pull request #25
Opened 2022-01-15 11:38 UTC by fabio-ivona

This PR enable tests and ensures support for each version of Laravel (7 - 8 - 9)

TODO:

- [ ]  fix `->assertDeleted()` not found for Laravel 9

2022-01-15 15:28 UTC, fabio-ivona commented
@owenvoke fixed the typo you pointed out here

https://github.com/pestphp/pest-plugin-laravel/pull/25/files#diff-aa1e62dc03b7627ccc31b47c8153ea9ea269483402b01aa3721784cd03ec67b6R10

2022-01-16 00:15 UTC, owenvoke approved these changes

2022-01-16 13:40 UTC, nunomaduro requested changes

2022-01-16 13:40 UTC, nunomaduro commented on .github/workflows/tests.yml
> +        php: [ 7.3, 7.4, 8.0 ]
Can you add php 8.1?

2022-01-16 15:05 UTC, fabio-ivona commented on .github/workflows/tests.yml
> +        php: [ 7.3, 7.4, 8.0 ]
Done!

2022-01-16 16:42 UTC, owenvoke approved these changes

2022-01-16 17:39 UTC, merged